--- #YAML:1.0
name:                Tree-File
version:             0.110
abstract:            store a data structure in a file tree
license:             perl
generated_by:        ExtUtils::MakeMaker version 6.31
distribution_type:   module
requires:     
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Ricardo Signes <rjbs@cpan.org>
